preprocess:
  normalize_pcts: [0.5, 99.5]
  n4_bias_correction: false
  gaussian_filter: true
  nlm_denoising: false
  clahe: false
  gaussian_sigma: 1.0

seeding:
  class: 3
  min_bg_size : 5000
  max_bg_size : 200000

post:
  radius: 1
