preprocess:
  normalize_pcts: [0.5, 99.5]
  n4_bias_correction: false
  gaussian_filter: false
  nlm_denoising: false
  anisotropic_diffusion: true
  ad_niter: 5
  ad_kappa: 20.0
  ad_gamma: 0.1
  ad_option: 1
  clahe: false
  clahe_clip_limit: 0.5
  gaussian_sigma: 1.0

seeds:
  method: otsu
  # margin: 0.1
  # grad_percentile: 70
  # erosion_um: 1.0

segmentation:
  n_boot: 8
  debug: false

post:
  radius: 1
